spring:
  application:
    name: identity
  datasource:
    url: jdbc:postgresql://136.228.158.126:3297/postgres
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: "vannraruos@gmail.com"
    password: "klmcbchpzqszhlhz"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://34.124.129.117:8082
logging:
  level:
    org:
      springframework:
server:
  port: 8082
